version: '3.6'

services:

  node:
    build:
      context: ./services/node
    volumes:
      - './services/node:/usr/src/app'
      - '/usr/src/app/node_modules'

  nginx:
    build:
      context: ./services/frontend
    volumes:
      - './services/frontend:/usr/share/nginx/html'
    ports:
     - 8080:80
    depends_on:
      - node